### ISSUE TITLE
Stop button

### ISSUE THREAD

**Issue by openhardwarecoza** [andrewhodel/reprapweb#4]
Unless I am stupid, I see no "stop" button (:

Had to kill node and press reset on printer

**Comment by openhardwarecoza** [comment]
Or is pause and then clear queue the correct steps?

**Comment by andrewhodel** [comment]
Pause then clear queue.

Andrew

**Comment by openhardwarecoza** [comment]
Ok, I'll combine the two into a single Stop button to avoid confusion
